version: '3.4'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    restart: always
    command: start-dev
    ports:
      - "8088:8080"
    environment:
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: keycloak.localhost
      KC_HOSTNAME_PORT: 8088
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/$POSTGRES_DB?ssl_allow
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    networks:
      - mynet

  postgres:
    container_name: porstgres
    image: docker.io/postgres:14
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet

networks:
  mynet:
    name: mynet
    driver: bridge
    external: true

volumes:
  postgres_data: